#!/bin/bash -ex
NAILGUN_DIR=../nailgun-nailgun-all-0.9.1
KOTLINC_DIR=~/dev/kotlinc

if [[ `ps aux | grep NGServer | grep -v grep` = "" ]]; then
  echo "Starting Nailgun server..."
  java -verbose:gc \
    -cp $NAILGUN_DIR/nailgun-server/target/classes:$KOTLINC_DIR/lib/kotlin-preloader.jar:$KOTLINC_DIR/lib/kotlin-compiler.jar \
    com.martiansoftware.nailgun.NGServer &
  sleep 1
fi

if [ pom.xml -nt .mvn-classpath ]; then
  rm -f .mvn-classpath
  mvn dependency:build-classpath -Dmdep.outputFile=.mvn-classpath
fi

for JAVA in `find target/generated-sources -name "*.java"`; do
  CLASS=$JAVA

  # replace target/generated-sources/grammars with target/classes
  CLASS=${CLASS/target\/generated-sources\/grammars\//target\/classes\/}

  CLASS=${CLASS/.java/.class}

  if [[ $JAVA -nt $CLASS ]]; then
    JAVAS="$JAVAS $JAVA"
  fi
done

if [ "$JAVAS" != "" ]; then
  echo "Compiling .java to .class"
  echo $JAVAS
  javac $JAVAS -d $PWD/target/classes -cp `cat .mvn-classpath`:target/classes
fi

for KT in `find src/main/kotlin -name "*.kt"` `find src/test/kotlin -name "*.kt"`; do
  CLASS=$KT

  # replace src/main/kotlin/ with target/classes
  CLASS=${CLASS/src\/main\/kotlin\//target\/classes\/}

  # replace src/test/kotlin/ with target/classes
  CLASS=${CLASS/src\/test\/kotlin\//target\/classes\/}

  if [[ $KT -nt ${CLASS/.kt/.class} && $KT -nt ${CLASS/.kt/Kt.class} ]]; then
    KTS="$KTS $KT"
  fi
done

if [ "$KTS" != "" ]; then
  echo "Compiling .kt to .class"
  echo $KTS
  time $NAILGUN_DIR/ng \
    org.jetbrains.kotlin.preloading.Preloader \
    org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
    $KTS \
    -d $PWD/target/classes \
    -cp `cat .mvn-classpath`:target/classes
fi

if [ "$1" == "run" ]; then
  java -cp `cat .mvn-classpath`:target/classes com.danstutzman.WebServerKt
elif [ "$1" == "test" ]; then
  java -cp `cat .mvn-classpath`:target/classes org.junit.platform.console.ConsoleLauncher \
    --scan-classpath target/test-classes -cp target/test-classes
fi
