#!/bin/bash -ex

mkdir -p target/js
~/dev/kotlinc/bin/kotlinc-js \
  `find src/main/kotlin -name *.kt` \
  -output target/js/build.js

echo "var kotlin = require('../../node_modules/kotlin/kotlin.patched.js');" > target/js/prepend.js
cat target/js/prepend.js target/js/build.js > target/js/build.js.new
mv target/js/build.js.new target/js/build.js

#if [ target/js/kotlin.min.js -nt node_modules/kotlin/kotlin.js ]; then
#  node_modules/.bin/uglifyjs --compress --mangle -- \
#    node_modules/kotlin/kotlin.js \
#    > target/js/kotlin.min.js
#fi

#node_modules/.bin/uglifyjs --compress --mangle -- \
#  target/js/build.js \
#  > target/js/build.min.js

#node -e "kotlin = require('./target/js/kotlin.min.js'); require('./target/js/build.min.js')"

echo "var process = undefined;" > target/js/externs.js

# Fixes for Google Closure Compiler advanced mode
cat node_modules/kotlin/kotlin.js \
  | sed 's/Kotlin.kotlin.js.internal.IntCompanionObject/Kotlin.kotlin.js.internal["IntCompanionObject"]/g' \
  | sed 's/this.equality\./this["equality"]./g' \
  > node_modules/kotlin/kotlin.patched.js

java -jar node_modules/google-closure-compiler/compiler.jar \
  --module_resolution NODE \
  --js node_modules/kotlin/kotlin.patched.js \
  --js node_modules/kotlin/package.json \
  --process_common_js_modules \
  --compilation_level ADVANCED \
  --externs target/js/externs.js \
  --warning_level QUIET \
  --create_source_map target/js/all.gcc.map \
  target/js/build.js \
  > target/js/all.gcc.js

# node_modules/.bin/source-map resolve target/js/all.gcc.map 184 227

node target/js/all.gcc.js
