package com.danstutzman.templates

import com.danstutzman.db.ArNounRow

fun GetArNouns(nounRows: List<ArNounRow>): String {
  val html = StringBuilder()
  html.append(OPEN_BODY_TAG)
  html.append("<a href='/'>Back to home</a>\n")
  html.append("<h1>Arabic Nouns</h1>\n")
  html.append("<form method='POST' action='/ar/nouns'>\n")
  html.append("<table border='1'>\n")
  html.append("  <tr>\n")
  html.append("    <th>LeafId</td>\n")
  html.append("    <th>English</td>\n")
  html.append("    <th>Buckwalter</td>\n")
  html.append("    <th>Pronunciation (Qalam)</td>\n")
  html.append("    <th>Monospace</td>\n")
  html.append("    <th>Gender</td>\n")
  html.append("    <th></td>\n")
  html.append("  </tr>\n")
  for (row in nounRows) {
    html.append("  <tr>\n")
    html.append("    <td>${row.leafId}</td>\n")
    html.append("    <td>${row.en}</td>\n")
    html.append("    <td class='ar-buckwalter' data-row-id='${row.leafId}'>${escapeHTML(row.arBuckwalter)}</td>\n")
    html.append("    <td><div id='ar-qalam-${row.leafId}' class='ar-qalam'></td>\n")
    html.append("    <td><div id='ar-monospace-${row.leafId}' class='ar-monospace'></td>\n")
    html.append("    <td>${row.gender}</td>\n")
    html.append("    <td><input type='submit' name='deleteLeaf${row.leafId}' value='Delete' onClick='return confirm(\"Delete noun?\")'></td>\n")
    html.append("  </tr>\n")
  }
  html.append("  <tr>\n")
  html.append("    <td></td>\n")
  html.append("    <td><input type='text' name='en'></td>\n")
  html.append("    <td><input type='text' id='ar-buckwalter-new' name='ar_buckwalter' class='ar-buckwalter' data-row-id='new'></td>\n")
  html.append("    <td><input type='text' id='ar-qalam-new' data-row-id='new'></td>\n")
  html.append("    <td><input type='text' id='ar-monospace-new' class='ar-monospace'></td>\n")
  html.append("    <td><select name='gender'><option></option><option>M</option><option>F</option></select></td>\n")
  html.append("    <td><input type='submit' name='newNoun' value='Insert'></td>\n")
  html.append("  </tr>\n")
  html.append("</table>\n")
  html.append("</form>\n")
  html.append(CLOSE_BODY_TAG)
  return html.toString()
}